### ISSUE TITLE
New image v1.2.1 and DB problem. Image won't start

### ISSUE THREAD

**Issue by burakksglu** [MedAziz11/Uptime-Kuma-Web-API#33]
Hello there,

There is an issue with the new image of v1.2.1. Both on Linux server and my local docker environment I got an error about ./db path. Looks like a permission issue.

I didn't change anything on the image just pull & run.

<img width="944" alt="image" src="https://user-images.githubusercontent.com/49399656/234578529-c8fbf295-e0a7-4939-9c62-4cef7de01566.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/49399656/234578543-157e0557-5ded-462f-9cdf-74e369529b78.png">

**Comment by iluvatyr** [comment]
Seems to be that the permissions for the db are wrong.  This has to be changed in the Dockerfile by MedAziz11, so that it gets the correct user and permissions.

The user that runs the container (appuser) has the id 100. So depending on the permissions on your filesystem/docker-volume, it will not be allowed to write

You can fix this by manually changing  the permissions or the owner of the directory
If you used a bind mount on your hosts filesystem use
` chown -R 100 /path-to-directory/uptime-kuma-api `
and if it is a docker volume, then use
docker run --rm -it -v kuma-api:/kuma alpine chown -R 100 /kuma `

**Comment by burakksglu** [comment]
Hey @iluvatyr, 

We've tried to fix that permission issue like this but it seems like there is no ../db path like in the docker-compose.yml example. Because the problem still exists even if I don't mount any persistent volume to the container. The first white log screen was from my Mac and there was no volume or filesystem mounted on that container. So the issue persists in the container itself I guess.

![image](https://user-images.githubusercontent.com/49399656/235749199-5aabe8aa-be55-416a-b94e-748e14019b34.png)

**Comment by iluvatyr** [comment]
Yes the problem is that the Dockerfile doesnt correctly set the permission and even if you do not mount the /db path, it will be there inside the container with the wrong owner/permissions.
I tested it, since I had the same problem like you and I was able to fix it by doing the steps I described

Just use a second container that also mounts this volume and has root user access.
Then change the owner or make the db world readable (chmod 777), like I described above 

` docker run --rm -it -v your-kuma-api-volume:/kuma alpine chown -R 100 /kuma `

**Comment by MedAziz11** [comment]
in your docker compose just add ./db:/db:rwx
that should do it , i updated the compose file take a look.
my apologies for the delay .

**Comment by burakksglu** [comment]
> in your docker compose just add ./db:/db:rwx that should do it , i updated the compose file take a look. my apologies for the delay . @burakksglu @iluvatyr

No worries, thank you both for the effort. But I believe I already have it:

![image](https://user-images.githubusercontent.com/49399656/236617453-8a0b7ca2-2106-4a18-9f85-2acc75b9198b.png)
